export enum FeaturesEnum {
  USER = 'user',
  USER_FOLLOW = 'user_follow',
  USER_ANIME = 'user_anime',
  ROLE = 'role',
  ROLE_PERMISSION = 'role_permission',
  ANIME = 'anime',
  PUBLICATION = 'publication',
  PUBLICATION_LIKE = 'publication_like',
  PUBLICATION_COMMENT = 'publication_comment',
  BANNER = 'banner',
  NOTIFICATION = 'notification',
  CHAT = 'chat',
  DISCUSSION = 'discussion',
  DISCUSSION_COMMENT = 'discussion_comment',
  DISCUSSION_LIKE = 'discussion_like',
  CATEGORY = 'category',
  PRODUCT = 'product',
  STOCK = 'stock',
  ORDER = 'order'
}